### ISSUE TITLE
camel unable to handle "n"

### ISSUE THREAD

**Issue by lenis0012** [epszaw/anycase#3]

**Comment by epszaw** [comment]
Could you please provide more details here?

**Comment by lenis0012** [comment]
@epszaw sorry for the late reply.
It doesnt seem to be able to handle single-character names or segments that are single chartacters.

"n", "ABC", "HelloFriendA" are all not supported I believe and throw an error.

**Comment by lenis0012** [comment]
Example:

```
Hint: C:\Users\0p1q9\Projects\nim-game\test.exe  [Exec]
C:\Users\0p1q9\Projects\nim-game\test.nim(3) test
C:\Users\0p1q9\.nimble\pkgs\anycase-0.1.1\anycase\camel.nim(7) camel
C:\Users\0p1q9\.choosenim\toolchains\nim-1.6.8\lib\system.nim(2621) []
C:\Users\0p1q9\.choosenim\toolchains\nim-1.6.8\lib\system\fatal.nim(53) sysFatal
Error: unhandled exception: value out of range: -1 notin 0 .. 9223372036854775807 [RangeDefect]
Error: execution of an external program failed: 'C:\Users\0p1q9\Projects\nim-game\test.exe '
```

**Comment by lenis0012** [comment]
Also, the last example camel("HelloFriendA") outputs "helloFriend" which is wrong. the last character is missing

**Comment by betofloresbaca** [comment]
I created this PR to fix the issue: https://github.com/epszaw/anycase/pull/5

**Comment by epszaw** [comment]
@betofloresbaca merged the PR
